sudo: required
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "node"

services:
  - docker

before_script:
  - docker pull mysql:5.7
  - docker run -d -p 3306:3306 -e "MYSQL_ROOT_PASSWORD=root" -e "MYSQL_DATABASE=test" mysql:5.7
  - cd src/; npm install

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=msfidelis/boreal
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO

script: npm run test