sudo: required
language: node_js
node_js:
  - "7"
  - "6"

services:
  - docker

before_script:
  - docker pull mysql:5.7
  - docker run -d -p 2201:3306 -e "MYSQL_ROOT_PASSWORD=root" -e "MYSQL_DATABASE=test" mysql:5.7
  - cd src/; npm install

script: npm run test